home_projects/home_projects/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path('users/', include('users.urls'))
]

home_projects/quotes/urls.py
from django.urls import path

from . import views

app_name = 'quotes'

urlpatterns = [
    path('', views.main, name='root'),
    path('<int:page>', views.main, name='root_paginate'),
    path('add_author/', views.add_author, name='add_author'),
    path('add_quote/', views.add_quote, name='add_quote'),
    path('toptentags/', views.top_ten_tags, name='top_ten_tags'),
    path('quote/<int:quote_id>/', views.quote_detail, name='quote_detail'),
    path('quotes/tag/<str:tag_name>/', views.quotes_by_tag, name='quotes_by_tag')
]

home_projects/users/urls.py
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("signup/", views.signupuser, name="signup"),
    path("login/", views.loginuser, name="login"),
    path("logout/", views.logoutuser, name="logout"),
    path("profile/", views.profile, name="profile"),
    path("reset-password/", views.ResetPasswordView.as_view(), name="password_reset"),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

home_projects/quotes/models.py
from django.db import models


# Create your models here.
class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.fullname


class Tag(models.Model):
    name = models.CharField(max_length=90, unique=True, null=False)

    def __str__(self):
        return self.name


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

home_projects/quotes/forms.py
from django import forms
from .models import Author, Quote


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']


class QuoteForm(forms.ModelForm):
    class Meta:
        model = Quote
        fields = ['quote', 'tags', 'author']

home_projects/quotes/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.db.models import Count
from .forms import AuthorForm, QuoteForm
from .models import Quote, Tag


# Create your views here.
def main(request, page=1):
    quotes = Quote.objects.all()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request, 'quotes/index.html', context={'quotes': quotes_on_page})


def add_author(request):
    if not request.user.is_authenticated:
        return redirect(to='users:signin')
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:root')
    else:
        form = AuthorForm()
    return render(request, 'quotes/add_author.html', {'form': form})


def add_quote(request):
    if not request.user.is_authenticated:
        return redirect(to='users:signin')
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:root')
    else:
        form = QuoteForm()
    return render(request, 'quotes/add_quote.html', {'form': form})


def top_ten_tags(request):
    top_tags = Tag.objects.annotate(num_quotes=Count('quote')).order_by('-num_quotes')[:10]
    return render(request, 'quotes/top_ten_tags.html', {'top_tags': top_tags})


def quote_detail(request, quote_id):
    quote = Quote.objects.get(pk=quote_id)
    return render(request, 'quotes/quote_detail.html', {'quote': quote})


def quotes_by_tag(request, tag_name):
    quotes = Quote.objects.filter(tags__name__iexact=tag_name)
    all_tags = Tag.objects.all()
    return render(request, 'quotes/index.html', {'quotes': quotes, 'all_tags': all_tags, 'tag_name': tag_name})


def all_quotes(request):
    all_tags = Tag.objects.all()
    return render(request, 'quotes/index.html', {'all_tags': all_tags})

home_projects/quotes/templates/quotes/add_author.html
{% extends 'quotes/base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Додати автора</button>
    </form>
{% endblock %}

home_projects/quotes/templates/quotes/add_quote.html
{% extends 'quotes/base.html' %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Додати цитату</button>
    </form>
{% endblock %}

home_projects/quotes/templates/quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/styles.css' %}">
    <title>Homework</title>
</head>
<body>

<div class="container">
    <div class="row header-box pt-3 mb-3">
        <div class="col-md-8">
            <h1>
                <a href="/" style="text-decoration: none">Quotes to Scrape</a>
            </h1>
        </div>
        <div class="col-md-4">
            <p>

                {% if user.is_authenticated %}
                <a href="{% url 'quotes:add_author' %}" class="btn btn-primary">Додати автора</a>
                <a href="{% url 'quotes:add_quote' %}" class="btn btn-success">Додати цитату</a>
            <form method="post" action="{% url 'users:logout' %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Logout</button>
            </form>

            {% else %}
            <a href="{% url 'users:signup' %}" class="btn btn-primary">Register</a>
            <a href="{% url 'users:login' %}" class="btn btn-success">Login</a>
            {% endif %}

            <a href="{% url 'quotes:top_ten_tags' %}" class="btn btn-info">Top Ten Tags</a>
            </p>
        </div>
    </div>


    {% block content %}
    {% endblock %}

</div>
</body>
</html>

home_projects/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}

{% block content %}

<div class="row">

    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">
            {{quote.quote}}
            </span>
            <span>by <small class="author" itemprop="author">{{quote.author}}</small>
        <a href="{% url 'quotes:quote_detail' quote.id %}">(about)</a>
        </span>
            <div class="tags">
                Tags:
                {% if quote.tags.all %}
                    {% for tag in quote.tags.all %}
                        <a class="tag" href="{% url 'quotes:quotes_by_tag' tag.name %}">{{ tag.name }}</a>
                    {% endfor %}
                {% else %}
                    <span>No tags available</span>
                {% endif %}

            </div>
        </div>
        {% endfor%}
        <nav>
            <ul class="pager">
                <li class="previous">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                       href="{% if quotes.has_previous %}{% url 'quotes:root_paginate' quotes.previous_page_number %}{% endif %}">
                        Previous
                    </a>
                </li>
                <li class="next">
                    <a class="{% if not quotes.has_next %} disabled {% endif %}"
                       href="{% if quotes.has_next %}{% url 'quotes:root_paginate' quotes.next_page_number %}{% endif %}">
                        Next
                    </a>
                </li>
            </ul>
        </nav>

    </div>

</div>

{% endblock %}

home_projects/quotes/templates/quotes/quote_detail.html
{% extends 'quotes/base.html' %}

{% block content %}
    <h1>{{ quote.author.fullname }}</h1>
    <p>
        <strong>Born:</strong> {{ quote.author.born_date }} in {{ quote.author.born_location }}
    </p>
    <p>
        <strong>Description:</strong> {{ quote.author.description }}
    </p>

{% endblock %}

home_projects/quotes/templates/quotes/quotes_by_tag.html
{% extends 'quotes/base.html' %}

{% block content %}
    <h3>Viewing tag: <a href="/tag/{{ tag_name }}/page/1/">{{ tag_name }}</a></h3>

    <div class="row">
        <div class="col-md-8">
            {% for quote in quotes %}
            <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
                <span class="text" itemprop="text">{{ quote.text }}</span>
                <span>by <small class="author" itemprop="author">{{ quote.author.name }}</small>
                    <a href="/author/{{ quote.author.slug }}">(about)</a>
                </span>
                <div class="tags">
                    Tags:
                    {% for tag in quote.tags.all %}
                    <a class="tag" href="{% url 'quotes:quotes_by_tag' tag.name %}">{{ tag.name }}</a>
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
    </div>
            </div>
{% endblock %}

home_projects/quotes/templates/quotes/top_ten_tags.html
{% extends 'quotes/base.html' %}

{% block content %}
    <h2>Top Ten Tags</h2>
    <ul>
    {% for tag in top_tags %}
        <li>{{ tag.name }} ({{ tag.num_quotes }} quotes)</li>
    {% endfor %}
    </ul>
{% endblock %}